### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by anatolzak** [vahiwe/Elastic-Beanstalk-Single-Instance-SSL#1]
Hey! 

Thanks so much for writing such a helpful article on how to set up SSL for single-instance environments on EB!

I tried to create an app on EB with your code, but I get `502 Bad Gateway` when I go to my custom domain with HTTPS.

I tried debugging what was happening and can see that when I go to the EB URL, I get a security risk warning saying that the certificate for my custom domain is not valid for the EB URL. 

So I know that the certificate was successfully created for my custom domain.

But I can't figure out why I get `502` when I go to my custom domain via HTTPS. 
I looked into the logs but don't see anything wrong.

I was wondering if you might have an idea for what might be going wrong.

Thanks so much in advance!

**Comment by vahiwe** [comment]
Hello @anatolzak 
I'm glad you found the article.
I'm not 100% sure about the issue you’re having but my guess is you’re making use of the domain created by Elastic Beanstalk. You shouldn’t do that though once you’ve applied the configuration. You’re meant to make use of your personal domain and not the domain created by Elastic beanstalk. 
Let me know if you still have this issue.

**Comment by anatolzak** [comment]
Hey @vahiwe! Thanks for responding. 

When I was referring to my "custom domain", I meant the domain I bought, not the EB domain. I got the certificate for the domain I bought and when I visit it, I get `502 Bad Gateway` like I described.

**Comment by vahiwe** [comment]
Hello @anatolzak 
Thanks for the extra info.
Does HTTP work?

**Comment by anatolzak** [comment]
The code was configured to redirect HTTP requests to HTTPS. 

I will try disabling the redirect from HTTP to HTTPS and then check if I can access the site with HTTP through the domain I bought.

**Comment by vahiwe** [comment]
Okay
Try http before reconfiguring to use https

**Comment by anatolzak** [comment]
So I removed the line `return 301 https://$host$request_uri;` from `.platform/nginx/conf.d/https_custom.conf` to stop the redirect from HTTP to HTTPS in order to test whether HTTP works.

So HTTP works both on the EB domain and on the domain I bought. 

But I don't get the correct HTML page as shown in your article. Here is what I get:

<img width="2048" alt="image" src="https://user-images.githubusercontent.com/53095479/127742141-139a7207-0aaf-4a39-97a1-b00579724698.png">

Then, I tried going to the site through HTTPS with the domain I bought, and I get `502 Bad Gateway`

**Comment by vahiwe** [comment]
Hello @anatolzak 
What stack is your application running on?
Also is it a public project or repo I can look at?

**Comment by anatolzak** [comment]
> What stack is your application running on?

<img width="667" alt="image" src="https://user-images.githubusercontent.com/53095479/127774737-2109c0e9-829e-4295-a102-7673ee6f616a.png">

> Also is it a public project or repo I can look at?
Here is the git repo: https://github.com/anatolzak/Elastic-Beanstalk-Single-Instance-SSL

Here is the Elastic Beanstalk URL: http://nodejs-single-instance-example.us-east-2.elasticbeanstalk.com/
And here is the domain I bought: http://test.anatolz.com/

**Comment by vahiwe** [comment]
Hello @anatolzak 
I was able to replicate the issue on my end.
I've updated the article with the fix.
The nodejs application was running on port 8000 instead of 3030 which is the port nginx is routing requests to.
so the fix was to explicitly set the port in the environment variable which you’ll see in the article.
Sorry for the inconvenience caused.
Give it a go in a new environment and let me know the outcome.
Reference the article to see the changes.

**Comment by anatolzak** [comment]
Hi @vahiwe! Thanks for working out a fix.
I can now access the site over HTTPS on the domain I bought by adding the environment variable `PORT` and setting it to `3030`

There is still one problem that I am having. When I access the site over HTTP, I get the following page:

<img width="2039" alt="image" src="https://user-images.githubusercontent.com/53095479/127881762-013cafcf-c0e4-4175-9f4b-5f5748c11a41.png">

Over HTTPS, I get the correct page.

<img width="2048" alt="image" src="https://user-images.githubusercontent.com/53095479/127881838-ae4cac82-5f67-41ed-97f7-ac8598f41a74.png">

You can see it here http://test.anatolz.com/  and here https://test.anatolz.com/

**Comment by vahiwe** [comment]
Re-add this line `return 301 https://$host$request_uri;` you removed earlier. That is what redirects HTTP to HTTPS.

**Comment by anatolzak** [comment]
I re-added the redirect from HTTP to HTTPS and everything works perfectly now.

Thanks so much for your help!

**Comment by vahiwe** [comment]
You’re welcome @anatolzak.
Good luck with your project.

**Comment by anatolzak** [comment]
Thank you! 🙂
