### ISSUE TITLE
Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again

### ISSUE THREAD

**Issue by pc386** [vahiwe/Elastic-Beanstalk-Single-Instance-SSL#3]
When I deploy to beanstalk it fails on the step `40_installcertbot` with the message:
`Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again`

Any tips?

**Comment by Pingu69** [comment]
I redeployed and problem resolved itself

**Comment by vahiwe** [comment]
Glad you sorted it out @Pingu69
