### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by Uchihinha** [vahiwe/Elastic-Beanstalk-Single-Instance-SSL#5]
I tried exactly the same configuration but it doesn't work in my case. I'm using Elastic Beanstalk for a single instance, running a nodejs application into the port 3333, and yeah, I changed the port. Does the configuration changed?

**Comment by vahiwe** [comment]
Does the deployment complete?

**Comment by gherciu** [comment]
@vahiwe 
I get this error
```
Error occurred during build: Command 50_getcert failed
```

**Comment by vahiwe** [comment]
which amazon linux is being used @Gherciu ?

**Comment by Uchihinha** [comment]
@vahiwe just changed some settings here and it's working now, just one more question, is the cron configured to renew the certificate? If so, how is it working? Because the content is just a simple string "@weekly root certbot renew\n"

**Comment by vahiwe** [comment]
@Uchihinha cron utility on Linux knows to read that file and then it does the following:

- runs it weekly
- uses the root user
- runs the command `certbot renew`

**Comment by Uchihinha** [comment]
@vahiwe awesome, thanks a lot for this tutorial, it really helped me!
